import {assess} from './guidance.js';
const $=id=>document.getElementById(id);const KEY='ai_clinic_premium_demo_v1';
let state={messages:[],answers:{},followups:[],stage:0,report:null,booking:null,handed:false};let selectedDoctor=null,selectedDate=null,selectedTime=null;
const questions=[{q:'When did this concern begin?',key:'onset',choices:['Today','Yesterday','A few days ago','Not sure']},{q:'Do you have severe pain, significant swelling, or difficulty moving the affected area?',key:'severity',choices:['No','Mild swelling or pain','Severe pain or swelling','Difficulty moving','Not applicable']},{q:'Are you experiencing any warning signs, such as numbness, a change in color or shape, an open wound, severe bleeding, chest pain or difficulty breathing?',key:'flags',choices:['None of these','Numbness','Change in color or shape','Open wound','Severe bleeding','Chest pain or trouble breathing']},{q:'What would you like help preparing for your clinician?',key:'goal',choices:['General information','Find a specialist','Prepare a consultation summary','All three']}];
const doctors=[{id:0,name:'Dr. Amina Sadykova',initials:'AS',role:'General practitioner',specialty:'General practice',languages:'English · Kazakh',format:'Video · In-person',slots:['09:30','11:00','14:30']},{id:1,name:'Dr. Daniel Lee',initials:'DL',role:'Orthopedic specialist',specialty:'Orthopedics',languages:'English',format:'Video · In-person',slots:['10:00','13:00','16:00']},{id:2,name:'Dr. Maya Karim',initials:'MK',role:'Primary care clinician',specialty:'General practice',languages:'Kazakh · English',format:'Video · In-person',slots:['09:00','12:30','15:00']}];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function bubble(role,message){state.messages.push({role,message});renderMessages();persist()}
function renderMessages(){const area=$('messages');area.replaceChildren();state.messages.forEach(m=>{const d=document.createElement('div');d.className='bubble '+m.role;d.textContent=m.message;area.append(d)});area.scrollTop=area.scrollHeight;const quick=$('quickChoices');if(quick)quick.remove();if(state.stage>0&&state.stage<=questions.length){const row=document.createElement('div');row.className='quick';row.id='quickChoices';questions[state.stage-1].choices.forEach(c=>{const b=document.createElement('button');b.textContent=c;b.type='button';b.onclick=()=>receive(c);row.append(b)});area.after(row)}}
function ask(){if(state.stage<=questions.length){bubble('ai',questions[state.stage-1].q)}else{bubble('ai','Thank you. Your preliminary report is ready. Select “Analyse consultation” to view general guidance, source references and demonstration specialists.')}}
function receive(value){const v=value.trim();if(!v)return;if(state.stage===0){state.answers.concern=v;state.stage=1;bubble('user',v);const isEmergency=/chest pain|can't breathe|cannot breathe|unconscious|severe bleeding|stroke|difficulty breathing/i.test(v);if(isEmergency)bubble('ai','Your description may include an emergency warning sign. Seek immediate local emergency assistance now; do not wait for this demonstration.');ask()}else if(state.stage<=questions.length){state.answers[questions[state.stage-1].key]=v;state.stage++;bubble('user',v);if(/severe bleeding|chest pain|trouble breathing/i.test(v))bubble('ai','You selected a potentially serious warning sign. Seek immediate local emergency assistance; this demonstration cannot assess or manage emergencies.');ask()}else handleFollowup(v);$('messageInput').value='';updateProgress();persist()}
// After the initial intake, accept multiple additional symptoms and questions in the same session.
// Answers are from a narrow reviewed educational library, never generated diagnoses.
function handleFollowup(v){
 state.followups=state.followups||[];
 state.followups.push(v);
 bubble('user',v);
 const context=[state.answers.concern,...state.followups].join(' ');
 const guide=assess(context,extractFlags(context,state.answers));
 const q=v.toLowerCase();
 const asksCare=/what|how|should|recommend|suggest|avoid|do now|help|cold|ice|compress|move|rest|не істе|болмай|можно|делать|нельзя/.test(q);
 if(guide.urgent){bubble('ai','You may have reported a warning sign. Seek prompt in-person medical assessment; for severe bleeding, chest pain, breathing difficulty, or a serious injury, contact local emergency services. Do not wait for this app or a fictional booking.');}
 else if(guide.recognized && asksCare){bubble('ai',guide.guidance+'\n\nSource: NHS Hand pain and MedlinePlus First Aid (linked in your report). These are general educational steps, not a personal treatment plan.');}
 else if(guide.recognized){bubble('ai','I added that detail to this consultation. You can ask several more questions, such as “What can I do while waiting?” or “What should I avoid?” and then select Analyse consultation to refresh your report.');}
 else{bubble('ai','I saved your additional question for the clinician. This topic is outside my limited reviewed offline guidance. I cannot safely suggest a condition-specific treatment. You can keep adding details or update your report.');}
 if(state.report)makeReport(false);
 updateProgress();persist();
}
function extractFlags(context,answers){
 const n=context.toLowerCase(), s=(answers.flags||'').toLowerCase(), sev=(answers.severity||'').toLowerCase();
 return {'numbness':s.includes('numb')||/\bnumb(ness)?\b|loss of sensation/.test(n),
 'cannot move':sev.includes('difficulty moving')||/can(?:not|'t) move|unable to move/.test(n),
 'severe pain':sev.includes('severe')||/severe pain|unbearable pain/.test(n),
 'changed shape':s.includes('shape')||/deform|changed shape|looks crooked/.test(n),
 'blue or pale':s.includes('color')||/turned blue|turned pale|blue fingers/.test(n),
 'open wound':s.includes('wound')||/open wound|deep cut/.test(n),
 'fever':/\bfever\b/.test(n)};
}
function updateProgress(){$('step').textContent='STEP '+Math.min(3,Math.max(1,Math.ceil(state.stage/2)))+' OF 3';$('progressFill').style.width=(10+Math.min(90,state.stage*19))+'%';$('summaryBits').textContent=(state.answers.concern?'Concern: '+state.answers.concern+'\n':'')+(state.answers.onset?'Onset: '+state.answers.onset+'\n':'')+(state.answers.severity?'Severity reported: '+state.answers.severity:'')||'Your consultation summary will appear here as you chat.'}
function makeReport(scroll=true){if(!state.answers.concern){bubble('ai','Please describe your concern first.');return}const a=state.answers;const all=[a.concern,...(state.followups||[])].join(' ');const guide=assess(all,extractFlags(all,a));const emergency=/severe bleeding|chest pain|trouble breathing/i.test(a.flags||'')||/chest pain|can't breathe|cannot breathe|unconscious|severe bleeding|stroke|difficulty breathing/i.test(all);const warning=emergency||guide.urgent;const hand=guide.topic==='hand';state.report={guide,emergency,warning,hand,answers:{...a},followups:[...(state.followups||[])],created:new Date().toISOString()};persist();renderReport();renderDoctors();$('reportSection').classList.remove('hidden');$('handover').disabled=!$('consent').checked;if(scroll)$('reportSection').scrollIntoView({behavior:'smooth',block:'start'});}
function card(title,body,warning=false){const d=document.createElement('article');d.className='reportCard'+(warning?' warning':'');const h=document.createElement('h3');h.textContent=title;d.append(h);const p=document.createElement('p');p.textContent=body;d.append(p);return d}
function renderReport(){const r=state.report;if(!r)return;const area=$('report');area.replaceChildren();area.append(card('01 · Patient-reported information',`Concern: ${r.answers.concern}\nOnset: ${r.answers.onset||'Not reported'}\nReported severity: ${r.answers.severity||'Not reported'}\nOther reported signs: ${r.answers.flags||'Not reported'}\nAdditional questions and symptoms: ${(r.followups||[]).join(' | ')||'None'}`));area.append(card('02 · Preliminary information & uncertainty',r.guide.recognized?'Your description matches the limited hand-injury information topic. This is not a diagnosis. A fracture or other injury cannot be ruled out online.':'This concern is outside the reviewed condition-specific topics in this prototype. No diagnosis or condition-specific conclusion can be made.'));area.append(card('03 · General guidance',r.emergency?'Potential emergency warning sign reported. Contact local emergency services now. Do not wait for an online appointment.':r.guide.guidance,r.warning));area.append(card('04 · Warning signs & next step',r.emergency?'Emergency warning sign reported: immediate local emergency assistance is appropriate.':r.warning?'A warning sign was reported. Seek prompt in-person professional assessment. A demonstration booking is not a substitute.':'No listed warning signs were selected, but this does not exclude a serious condition. Seek professional advice if symptoms persist, worsen or concern you.',r.warning));area.append(card('05 · Suggested specialty',r.hand?'Orthopedics or primary care may be relevant for a hand injury. This is a demonstration directory match, not a clinical referral.':'A general practitioner can help determine the appropriate next step. This is a directory suggestion, not clinical triage.'));const refs=document.createElement('article');refs.className='reportCard';refs.innerHTML='<h3>06 · Medical references</h3><p>External sources require an internet connection. Links are for further reading; no live database retrieval occurs.</p>';const ul=document.createElement('ul');const sources=[...r.guide.sources,['MedlinePlus — Health Topics','https://medlineplus.gov/healthtopics.html'],['PubMed — Biomedical literature search','https://pubmed.ncbi.nlm.nih.gov/']];sources.forEach(([label,url])=>{const li=document.createElement('li'),link=document.createElement('a');link.textContent=label;link.href=url;link.target='_blank';link.rel='noopener noreferrer';li.append(link);ul.append(li)});refs.append(ul);area.append(refs);$('matchReason').textContent=r.hand?'Suggested directory category: Orthopedics or general practice, because the patient reported a hand injury. Not a clinical referral.':'Suggested directory category: General practice, to discuss the concern and determine an appropriate next step. Not a clinical referral.';}
function renderDoctors(){const root=$('doctors');root.replaceChildren();const order=state.report?.hand?[doctors[1],doctors[0],doctors[2]]:doctors;order.forEach(d=>{const el=document.createElement('article');el.className='doctor';el.innerHTML=`<div class="docTop"><div class="avatar">${d.initials}</div><div><h3>${esc(d.name)}</h3><small>${esc(d.role)}</small></div></div><div class="meta">◈ ${esc(d.format)}<br>◎ ${esc(d.languages)}<br>▦ Fictional demonstration schedule</div>`;const b=document.createElement('button');b.className='btn';b.textContent='View demo availability ↗';b.onclick=()=>openBooking(d);el.append(b);root.append(el)})}
function openBooking(d){selectedDoctor=d;selectedTime=null;selectedDate=null;const p=$('bookingPanel');p.classList.remove('hidden');p.replaceChildren();const h=document.createElement('h3');h.textContent='Reserve a fictional consultation with '+d.name;p.append(h);const info=document.createElement('p');info.textContent='Demonstration only. No real clinician, appointment, payment or video call.';p.append(info);const dates=document.createElement('div');dates.className='dateSlots';for(let i=1;i<=4;i++){const date=new Date();date.setDate(date.getDate()+i);const label=date.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});const b=document.createElement('button');b.className='slot';b.textContent=label;b.onclick=()=>{selectedDate=label;dates.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');updateBookingButton()};dates.append(b)}p.append(dates);const times=document.createElement('div');times.className='dateSlots';d.slots.forEach(t=>{const b=document.createElement('button');b.className='slot';b.textContent=t;b.onclick=()=>{selectedTime=t;times.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');updateBookingButton()};times.append(b)});p.append(times);const book=document.createElement('button');book.id='confirmBooking';book.className='btn';book.textContent='Confirm fictional appointment';book.disabled=true;book.onclick=()=>{state.booking={doctor:d.name,date:selectedDate,time:selectedTime,reference:'DEMO-'+Date.now().toString().slice(-6)};persist();const notice=document.createElement('p');notice.style.color='#158261';notice.textContent=`✓ Fictional reservation confirmed: ${d.name} · ${selectedDate} at ${selectedTime}. Reference ${state.booking.reference}. Saved only in this browser.`;p.append(notice);book.disabled=true};p.append(book);p.scrollIntoView({behavior:'smooth',block:'center'})}
function updateBookingButton(){const b=$('confirmBooking');if(b)b.disabled=!selectedDate||!selectedTime}
function summaryText(){const r=state.report;if(!r)return 'No report';return `AI CLINIC · FICTIONAL DEMONSTRATION\nNot a medical diagnosis or clinical record\n\nFictional patient: ${$('alias').value||'Demo patient'}\nConcern: ${r.answers.concern}\nOnset: ${r.answers.onset||'Not reported'}\nSeverity: ${r.answers.severity||'Not reported'}\nWarning signs: ${r.answers.flags||'Not reported'}\nAdditional questions and symptoms: ${(r.followups||[]).join(' | ')||'None'}\n\nGeneral guidance: ${r.emergency?'Seek immediate local emergency assistance.':r.guide.guidance}\nSuggested directory category: ${r.hand?'Orthopedics or general practice':'General practice'}\n\nReferences:\n${r.guide.sources.map(s=>s.join(' — ')).join('\n')}\n\n${state.booking?`FICTIONAL booking: ${state.booking.doctor}, ${state.booking.date}, ${state.booking.time}`:''}\nNo clinical validation or real clinician connection.`}
$('chatForm').onsubmit=e=>{e.preventDefault();receive($('messageInput').value)};$('analyse').onclick=makeReport;$('consent').onchange=()=>{$('handover').disabled=!$('consent').checked||!state.report};$('handover').onclick=()=>{if(!$('consent').checked||!state.report)return;state.handed=true;persist();$('handoverStatus').textContent=navigator.onLine?'Simulated handover completed in this browser. No server transmission.':'Offline: simulated handover queued locally; no server transmission.';$('inboxText').textContent='Fictional consultation received: '+($('alias').value||'Demo patient')+' — '+state.answers.concern+'. Human review required.'};$('download').onclick=()=>{const blob=new Blob([summaryText()],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AI-Clinic-Demo-Summary.txt';a.click();URL.revokeObjectURL(url)};$('reset').onclick=()=>{if(!confirm('Delete this browser’s fictional demonstration data?'))return;localStorage.removeItem(KEY);location.reload()};$('photo').onchange=e=>{const f=e.target.files?.[0],area=$('preview');area.replaceChildren();if(!f)return;if(!f.type.startsWith('image/')||f.size>5e6){area.textContent='Choose an image smaller than 5 MB.';return}const url=URL.createObjectURL(f),img=document.createElement('img');img.alt='Local preview only; not analyzed';img.src=url;img.onload=()=>URL.revokeObjectURL(url);area.append(img);const note=document.createElement('p');note.textContent='Preview only. No AI image assessment, storage or upload.';area.append(note)};function network(){$('net').textContent=navigator.onLine?'● Online':'○ Offline';$('net').style.color=navigator.onLine?'#168265':'#a86b20'}window.addEventListener('online',network);window.addEventListener('offline',network);$('language').onchange=e=>{if(e.target.value==='kk')bubble('ai','Қазақша нұсқасы: өз шағымыңызды жазыңыз. Бұл медициналық диагноз емес. Толық клиникалық нұсқаулық әзірге ағылшын тілінде берілген.');else bubble('ai','English selected. Continue your consultation below.')};try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.messages&&Array.isArray(s.messages)){state=s;state.followups=state.followups||[]}}catch{}if(!state.messages.length)bubble('ai','Hello. I’m your AI Clinic consultation assistant. I can help organize your concern and show general reference-based information. I cannot diagnose conditions or interpret photographs.\n\nTo begin, what is troubling you today?');else renderMessages();updateProgress();renderDoctors();if(state.report){renderReport();$('reportSection').classList.remove('hidden')}if(state.handed)$('inboxText').textContent='A fictional consultation was shared in this browser. Human review required.';network();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
