import {classify} from './model.js';
const $=id=>document.getElementById(id);const KEY='carebridge_demo_v1';let current=null;let received=[];
const dictionary={
 en:{pilot:'RESEARCH PROTOTYPE · NO MEDICAL DIAGNOSIS',title:'Care starts before the connection.',intro:'Record your concerns offline. Organize a clear intake summary. Share it with a clinician only when you choose.',intake:'Patient intake',safety:'Not for emergencies or diagnosis. If you may need urgent medical help, contact local emergency services or seek immediate in-person care. Do not wait for this app.',alias:'Patient nickname (fictional demo only)',notes:'Describe your concern or what you need from the clinic',duration:'When did this concern begin? (optional)',photo:'Optional photo for clinician review only',photoNote:'Images are not analyzed by AI, stored, or uploaded in this demo.',prepare:'Prepare offline summary',summary:'Prepared consultation',empty:'Complete the intake form to generate a structured summary.',sync:'Consent-controlled handover',consent:'I understand this is a fictional demonstration and authorize sharing this summary with the simulated clinic.',send:'Send to simulated clinic',clear:'Delete local intake',clinician:'Simulated clinician dashboard',clinicInfo:'This is an in-browser demonstration, not a real doctor connection or secure clinical record system.',how:'What the on-device AI does',ai:'A bundled multilingual Naive Bayes model classifies administrative requests (appointments, clinic information, records, follow-up). It abstains when uncertain. It does not interpret symptoms, assess urgency, diagnose conditions, analyze photos or choose specialists.',privacy:"Privacy: demo data remains in this browser’s local storage until deleted. Use invented information only. Production use would require encryption, access controls, clinical validation and compliant infrastructure.",online:'Online · simulated handover available',offline:'Offline · intake remains available',unknown:'Needs human review',appointment:'Appointment request',clinic_info:'Clinic information',records:'Records handover',follow_up:'Follow-up request',received:'Simulated clinic received the summary.',queued:'No connection. Handover pending; reconnect to simulate delivery.',deleted:'Local intake deleted.',notshared:'Nothing shared yet.'},
 kk:{pilot:'ЗЕРТТЕУ ПРОТОТИПІ · МЕДИЦИНАЛЫҚ ДИАГНОЗ ҚОЙМАЙДЫ',title:'Көмек интернетсіз де басталады.',intro:'Өтінішіңізді офлайн жазыңыз. Қысқаша мәлімет дайындаңыз. Тек өз келісіміңізбен маманға жіберіңіз.',intake:'Пациент өтініші',safety:'Шұғыл көмекке немесе диагноз қоюға арналмаған. Шұғыл медициналық көмек қажет болса, жергілікті жедел қызметке хабарласыңыз немесе дереу дәрігерге барыңыз. Бұл қолданбаны күтпеңіз.',alias:'Пациенттің лақап аты (тек ойдан шығарылған мысал)',notes:'Шағымыңызды немесе емханадан не қажет екенін жазыңыз',duration:'Қашан басталды? (міндетті емес)',photo:'Дәрігер қарауы үшін фото (міндетті емес)',photoNote:'Бұл мысалда суреттерді ЖИ талдамайды, сақтамайды және жібермейді.',prepare:'Офлайн мәлімет дайындау',summary:'Дайын өтініш',empty:'Қысқаша мәлімет алу үшін нысанды толтырыңыз.',sync:'Келісіммен жіберу',consent:'Бұл ойдан шығарылған мысал екенін түсінемін және мәліметті сынақ емханасына жіберуге келісемін.',send:'Сынақ емханасына жіберу',clear:'Жергілікті деректерді өшіру',clinician:'Дәрігердің сынақ панелі',clinicInfo:'Бұл тек браузердегі көрсетілім, нақты дәрігермен байланыс немесе қорғалған медициналық жүйе емес.',how:'Құрылғыдағы ЖИ не істейді?',ai:'Жергілікті көптілді Naive Bayes моделі әкімшілік өтініштерді топтайды: қабылдауға жазылу, емхана ақпараты, құжаттар және қайта қаралу. Сенімсіз болса, шешімді адамға қалдырады. Симптомдарды талдамайды, шұғылдықты бағаламайды, диагноз қоймайды, суреттерді талдамайды және маманды таңдамайды.',privacy:'Құпиялық: сынақ деректері өшірілгенге дейін тек осы браузерде сақталады. Тек ойдан шығарылған деректерді қолданыңыз.',online:'Интернет бар · сынақ жіберу қолжетімді',offline:'Интернет жоқ · өтінішті толтыруға болады',unknown:'Маман тексеруі керек',appointment:'Қабылдауға жазылу',clinic_info:'Емхана ақпараты',records:'Құжаттарды жіберу',follow_up:'Қайта қаралу',received:'Сынақ емханасы мәліметті алды.',queued:'Интернет жоқ. Жіберу кезекте; қосылғанда сынақ түрде жеткізіледі.',deleted:'Жергілікті деректер өшірілді.',notshared:'Әзірге ештеңе жіберілген жоқ.'}}
let lang='en';const t=k=>dictionary[lang][k]||k;function elt(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
function render(){document.querySelectorAll('[data-i]').forEach(n=>n.textContent=t(n.dataset.i));$('network').textContent=navigator.onLine?t('online'):t('offline');$('result').replaceChildren();if(current){const x=current;$('result').append(elt('p',`ID: ${x.id}`),elt('p',`${t('alias')}: ${x.alias}`),elt('p',`${t('notes')}: ${x.notes}`),elt('p',`${t('duration')}: ${x.duration||'—'}`),elt('p',`AI administrative category: ${t(x.classification.category)}`),elt('p',`Model confidence: ${(x.classification.confidence*100).toFixed(0)}% (not clinical confidence)`),elt('p','Clinician must review original description. No diagnosis or triage performed.'));}else $('result').append(elt('p',t('empty')));$('handover').disabled=!current||!$('consent').checked;$('inbox').replaceChildren();if(!received.length)$('inbox').append(elt('p',t('notshared')));for(const r of received){const d=elt('div','');d.className='inbox';d.append(elt('strong',`${r.alias} · ${new Date(r.created).toLocaleString()}`),elt('p',r.notes),elt('p',`Category: ${t(r.classification.category)} · Requires human review`));$('inbox').append(d);}}
function save(){if(current)localStorage.setItem(KEY,JSON.stringify(current));else localStorage.removeItem(KEY);}
try{const stored=JSON.parse(localStorage.getItem(KEY));if(stored&&typeof stored.alias==='string'&&typeof stored.notes==='string')current=stored;}catch{localStorage.removeItem(KEY)}
$('lang').addEventListener('change',e=>{lang=e.target.value;document.documentElement.lang=lang;render();});$('consent').addEventListener('change',render);
$('photo').addEventListener('change',e=>{const f=e.target.files[0];$('preview').replaceChildren();if(f){if(!f.type.startsWith('image/')||f.size>5e6){alert('Image must be under 5 MB');e.target.value='';return;}const url=URL.createObjectURL(f),im=document.createElement('img');im.src=url;im.alt='Local preview for clinician review; not uploaded';im.onload=()=>URL.revokeObjectURL(url);$('preview').append(im);}});
$('form').addEventListener('submit',e=>{e.preventDefault();const alias=$('alias').value.trim(),notes=$('notes').value.trim();if(!alias||!notes)return;current={id:'DEMO-'+Date.now(),alias,notes,duration:$('duration').value.trim(),classification:classify(notes),created:new Date().toISOString(),pending:false};$('consent').checked=false;$('status').textContent='';save();render();});
function deliver(){if(!current||!current.pending||!navigator.onLine)return;received.push({...current});current.pending=false;save();$('status').textContent=t('received');render();}
$('handover').addEventListener('click',()=>{if(!current||!$('consent').checked)return;current.pending=true;save();if(navigator.onLine)deliver();else $('status').textContent=t('queued');});
$('clear').addEventListener('click',()=>{current=null;received=[];save();$('form').reset();$('preview').replaceChildren();$('consent').checked=false;$('status').textContent=t('deleted');render();});
window.addEventListener('online',()=>{deliver();render();});window.addEventListener('offline',render);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
