import {classify} from './model.js';import {assess} from './guidance.js';
const $=id=>document.getElementById(id),KEY='carebridge_upgrade_demo_v2';let current=null,received=[],lang='en',selected=null;
const kk=()=>lang==='kk';const txt=(en,kaz)=>kk()?kaz:en;
const doctors=[{name:'Dr. Amina Sadykova',role:'General practitioner',slots:['09:30','11:00','15:00']},{name:'Dr. Daniel Lee',role:'General practitioner',slots:['10:00','13:30','16:00']},{name:'Dr. Maya Karim',role:'Clinic intake nurse',slots:['09:00','12:00','14:30']}];
function node(tag,text){const el=document.createElement(tag);el.textContent=text;return el;}function line(parent,tag,text){parent.append(node(tag,text));}
function status(){ $('network').textContent=navigator.onLine?txt('Online · research links available','Онлайн · дереккөз сілтемелері қолжетімді'):txt('Offline · local guidance and demo booking available','Офлайн · жергілікті ақпарат пен сынақ жазылу қолжетімді'); }
function render(){status();$('result').replaceChildren();$('booking').replaceChildren();$('handover').disabled=!current||!$('consent').checked;
 if(!current){line($('result'),'p',txt('Describe your concern and press Analyse / Send.','Шағымды жазып, Талдау / Жіберу батырмасын басыңыз.'));return;}
 const a=current.assessment;line($('result'),'h3',txt('Preliminary consultation · information only','Алдын ала кеңес · тек ақпарат'));line($('result'),'p',`${current.alias} · ${current.notes}`);line($('result'),'p',txt('When it began: ','Қашан басталды: ')+(current.duration||'—'));
 const warning=node('p',a.guidance);warning.className=a.urgent?'notice':'guidance';$('result').append(warning);
 line($('result'),'h3',txt('Questions to discuss with a clinician','Дәрігермен талқылайтын сұрақтар'));const ul=node('ul','');a.questions.forEach(q=>ul.append(node('li',q)));$('result').append(ul);
 if(a.urgent){line($('result'),'p',txt('Warning signs selected: do not delay care for this demo booking.','Қауіпті белгілер: сынақ жазылуды күтіп қалмаңыз.'));}
 if(!a.recognized)line($('result'),'p',txt('No reviewed condition-specific guidance matched. Human review needed.','Тақырыпқа сәйкес тексерілген кеңес табылмады. Маман қарауы қажет.'));
 line($('result'),'h3',txt('Medical information sources','Медициналық ақпарат дереккөздері'));a.sources.forEach(([label,url])=>{const p=node('p',''),link=node('a',label);link.href=url;link.target='_blank';link.rel='noopener noreferrer';p.append(link,node('small',txt(' · Links require internet; the guidance above is available offline.',' · Сілтемелерге интернет қажет; жоғарыдағы ақпарат офлайн жұмыс істейді.')));$('result').append(p);});
 line($('booking'),'h3',txt('Fictional clinic · demonstration appointments','Ойдан шығарылған емхана · сынақ жазылу'));line($('booking'),'p',txt('These clinicians, schedules and bookings are fictional. No real appointments or video calls are made.','Дәрігерлер, кестелер мен жазылу — ойдан шығарылған. Нақты қабылдау немесе бейнеқоңырау жоқ.'));
 doctors.forEach((d,i)=>{const box=node('div','');box.className='doctor';line(box,'strong',d.name+' · '+d.role);const select=document.createElement('select');select.setAttribute('aria-label',d.name+' demonstration slot');d.slots.forEach(s=>{const opt=node('option',s+' · DEMO');opt.value=s;select.append(opt);});const btn=node('button',txt('Request demo appointment','Сынақ қабылдауға жазылу'));btn.type='button';btn.addEventListener('click',()=>{if(a.urgent){$('bookingStatus').textContent=txt('Warning signs were identified. Seek prompt in-person care; do not rely on a demo appointment.','Қауіпті белгілер анықталды. Дереу дәрігерге қаралыңыз.');return;}selected={doctor:d.name,slot:select.value};$('bookingStatus').textContent=txt('Fictional request saved locally: ','Ойдан шығарылған өтініш жергілікті сақталды: ')+d.name+' · '+select.value+' (DEMO)';});box.append(select,btn);$('booking').append(box);});
}
$('lang').addEventListener('change',e=>{lang=e.target.value;render();});$('consent').addEventListener('change',render);
$('photo').addEventListener('change',e=>{const f=e.target.files[0];$('preview').replaceChildren();if(f){if(!f.type.startsWith('image/')||f.size>5e6){alert('Please choose an image under 5MB');e.target.value='';return;}const img=document.createElement('img'),url=URL.createObjectURL(f);img.src=url;img.alt='Local preview only; not analyzed';img.onload=()=>URL.revokeObjectURL(url);$('preview').append(img);}});
$('form').addEventListener('submit',e=>{e.preventDefault();const alias=$('alias').value.trim(),notes=$('notes').value.trim();if(!alias||!notes)return;const answers={};document.querySelectorAll('.redflag').forEach(x=>answers[x.value]=x.checked);current={id:'DEMO-'+Date.now(),alias,notes,duration:$('duration').value.trim(),assessment:assess(notes,answers),classification:classify(notes),created:new Date().toISOString(),pending:false};localStorage.setItem(KEY,JSON.stringify(current));$('consent').checked=false;$('status').textContent='';$('bookingStatus').textContent='';render();});
function deliver(){if(!current||!current.pending||!navigator.onLine)return;received.push({...current});current.pending=false;localStorage.setItem(KEY,JSON.stringify(current));$('status').textContent=txt('Fictional clinic received the summary in this browser.','Осы браузердегі сынақ емханасы мәліметті алды.');showInbox();}
function showInbox(){$('inbox').replaceChildren();if(!received.length)line($('inbox'),'p','Nothing shared yet.');received.forEach(r=>{const div=node('div','');div.className='doctor';line(div,'strong',r.alias+' · '+new Date(r.created).toLocaleString());line(div,'p',r.notes);line(div,'p','Guidance topic: '+r.assessment.topic+' · Human clinician review required');$('inbox').append(div);});}
$('handover').addEventListener('click',()=>{if(!current||!$('consent').checked)return;current.pending=true;localStorage.setItem(KEY,JSON.stringify(current));if(navigator.onLine)deliver();else $('status').textContent='Offline: fictional handover queued in this browser.';});
$('clear').addEventListener('click',()=>{current=null;received=[];selected=null;localStorage.removeItem(KEY);$('form').reset();$('preview').replaceChildren();$('consent').checked=false;$('status').textContent='Local demo information deleted.';$('bookingStatus').textContent='';showInbox();render();});
window.addEventListener('online',()=>{status();deliver();});window.addEventListener('offline',status);try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.assessment)current=x;}catch{}render();showInbox();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
