// Conversation routing, not a medical device or validated clinical triage system.
const q=(question,key,choices)=>({q:question,key,choices});
const onset=q('When did this start, and is it getting worse?', 'onset',['Today','A few days ago','More than a week ago','Suddenly and getting worse','Other — I will explain']);
const history=q('Is there relevant medical history, pregnancy, medication, allergies or a previous episode you want to mention?', 'history',['None known','Yes — I will explain','Pregnant or possibly pregnant','Not sure / prefer not to say']);
const goal=q('What would you like help deciding?', 'goal',['Should I seek urgent care?','Can I discuss self-care with a clinician?','Which clinician should I contact?','I have another question']);
const sets={
 limb:[q('Which area hurts and did you fall, twist it or have another injury?', 'location',['Hand or wrist','Leg or knee','Ankle or foot','Arm or shoulder','No injury / other']),onset,q('Can you move the area and bear weight, if applicable?', 'mobility',['Yes, normally','Painful but possible','No, I cannot','Not sure']),q('Any deformity, severe swelling, numbness, color change or an open wound?', 'flags',['None reported','Deformity / possible fracture','Severe swelling or pain','Numbness or blue/cold limb','Open wound']),history,goal],
 abdominal:[q('Where is the pain or discomfort?', 'location',['Upper abdomen','Lower abdomen','Right side','Left side','All over','Not sure']),onset,q('What else is happening?', 'symptoms',['Nausea or vomiting','Diarrhea or constipation','Fever','Urinary symptoms','Pain only / other']),q('Any severe sudden pain, fainting, blood in vomit or stool, or possible pregnancy with pain?', 'flags',['None reported','Sudden severe pain','Blood in vomit or stool','Fainting / severe weakness','Possible pregnancy with pain']),history,goal],
 allergy:[q('What reaction are you noticing, and what might have triggered it?', 'symptoms',['Itchy rash / hives','Swelling','Food or medication exposure','Insect sting','Other']),q('Do you have trouble breathing, throat or tongue swelling, faintness, or rapidly worsening symptoms?', 'flags',['None reported','Trouble breathing','Throat or tongue swelling','Faint / rapidly worsening']),onset,history,goal],
 poisoning:[q('What substance or medication might have been involved? Please describe it, the amount if known, and how exposure happened.', 'substance',['Medication','Chemical or cleaning product','Food','Gas or fumes','Unknown — I will explain']),q('When did exposure occur?', 'onset',['Just now','Within a few hours','Earlier today','Earlier / unknown']),q('Any trouble breathing, confusion, fainting, seizures or severe symptoms?', 'flags',['None reported','Trouble breathing','Confusion or fainting','Seizure','Severe symptoms']),history,goal],
 chest:[q('Where is the discomfort, and what does it feel like?', 'location',['Chest pressure or tightness','Sharp chest pain','Palpitations','Other']),q('Any breathlessness, fainting, sweating, or pain spreading to arm, jaw or back?', 'flags',['None reported','Shortness of breath','Faintness / sweating','Pain spreading']),onset,history,goal],
 respiratory:[q('Which symptoms are you experiencing?', 'symptoms',['Cough','Fever','Sore throat','Congestion','Other']),onset,q('Any difficulty breathing, chest pain, blue lips or inability to swallow?', 'flags',['None reported','Difficulty breathing','Chest pain','Blue lips','Cannot swallow']),history,goal],
 neurological:[q('What are you experiencing?', 'symptoms',['Headache','Dizziness','Numbness or weakness','Vision changes','Other']),onset,q('Any sudden severe headache, new one-sided weakness, speech difficulty, confusion or fainting?', 'flags',['None reported','Sudden severe headache','One-sided weakness','Speech or vision changes','Confusion / fainting']),history,goal],
 skin:[q('What does the skin concern involve and where is it?', 'symptoms',['Rash / itching','Swelling','Pain / infection concern','Mole or skin change','Other']),onset,q('Any rapidly spreading redness, fever, facial swelling or breathing difficulty?', 'flags',['None reported','Rapid spread with fever','Face or lip swelling','Breathing difficulty']),history,goal],
 urinary:[q('What symptoms are present?', 'symptoms',['Pain with urination','Frequent urination','Flank / back pain','Blood in urine','Other']),onset,q('Any fever, severe flank pain, inability to pass urine, pregnancy or feeling very unwell?', 'flags',['None reported','Fever and flank pain','Unable to pass urine','Pregnancy with symptoms','Severely unwell']),history,goal],
 mental:[q('What would you like support with?', 'symptoms',['Anxiety / panic','Low mood','Sleep','Stress','Other']),q('Are you safe right now? If you may hurt yourself or someone else, contact emergency/crisis services now.', 'flags',['I am safe','Not sure','I may hurt myself','I need urgent help']),onset,history,goal],
 checkup:[q('What is the purpose of your visit?', 'symptoms',['Routine check-up','Vaccination','Screening','Review test results','Chronic condition follow-up']),q('Do you also have a new or worsening symptom?', 'flags',['No current symptoms','Yes — I will explain','New severe symptom']),history,goal],
 general:[q('Which part of your body or type of concern is involved? Please describe it in your own words.', 'symptoms',['Pain','Digestive or internal organ','Skin or allergy','Possible poisoning','Routine check-up','Other — I will explain']),onset,q('Do you have any severe, sudden or rapidly worsening symptoms?', 'flags',['None reported','Severe / rapidly worsening','Breathing difficulty','Fainting / confusion','Other — I will explain']),history,goal]
};
export function topicForConcern(input){const t=String(input).toLowerCase();if(/poison|overdose|swallow.*chemical|toxic|угар|отрав/.test(t))return 'poisoning';if(/allerg|anaphyl|hives|аллерг/.test(t))return 'allergy';if(/chest|heart|груд|сердц/.test(t))return 'chest';if(/stomach|abdomen|belly|liver|gallblad|pancrea|intestin|appendix|kidney pain|живот|желуд|печен/.test(t))return 'abdominal';if(/headache|migraine|dizz|vertigo|numb|paraly|голов.*бол|головокруж/.test(t))return 'neurological';if(/urina|pee|bladder|kidney|моч|почек/.test(t))return 'urinary';if(/leg|knee|foot|ankle|arm|shoulder|hand|finger|wrist|fractur|broken|sprain|нога|рука|колен|перелом/.test(t))return 'limb';if(/rash|itch|skin|eczema|mole|сыпь|кож/.test(t))return 'skin';if(/cough|fever|throat|cold|flu|breath|кашель|горло/.test(t))return 'respiratory';if(/mental|anxie|depress|panic|suicid|stress|тревог/.test(t))return 'mental';if(/check.up|checkup|annual|screening|vaccin|routine|профосмотр/.test(t))return 'checkup';return 'general'}
export function questionsFor(topic){return sets[topic]||sets.general}
const danger=/(?:trouble|difficulty|can't|cannot|hard to) breath|throat (?:is )?closing|tongue swelling|blue lips|seizure|unconscious|fainting|one.sided weakness|speech difficulty|sudden severe headache|severe chest pain|severe bleeding|want to die|hurt myself|suicid/i;
const negative=/^(?:no|none|none reported|none of these|i am safe|not applicable)$/i;
export function safetyScreen(input,topic,answers={}){
 const t=String(input||'').trim(),flag=String(answers.flags||'');
 if(negative.test(t)&&!flag)return {level:'unknown',message:''};
 if(topic==='poisoning')return {level:'urgent',message:'Possible poisoning needs immediate advice from your local poison-control service or emergency service, even before symptoms appear. Do not induce vomiting or take a home antidote. Keep the product container available if safe.'};
 if((danger.test(t)&&!/^\s*(?:no|not|without|deny|denies)\b/i.test(t))||/trouble breathing|throat or tongue swelling|confusion or fainting|seizure|one-sided weakness|speech or vision changes|i may hurt myself|i need urgent help/i.test(flag))return {level:'emergency',message:'A potentially serious warning sign was reported. Contact local emergency services now. Do not wait for this website or a demo appointment.'};
 if(/broken|fractur|can't walk|cannot walk|can't move|cannot move/i.test(t)||/deformity|severe swelling|unable to pass urine|fever and flank pain|sudden severe pain|blood in vomit|pregnancy with pain/i.test(flag))return {level:'prompt',message:'This could require prompt in-person assessment. Do not assume home care is sufficient; contact an appropriate medical service today.'};
 return {level:'unknown',message:'No listed emergency warning sign was identified by this limited prototype. This does not establish that self-care is safe.'};
}
export const specialties={limb:'Primary care, urgent care or orthopedics depending on findings',abdominal:'Primary care or urgent care; gastroenterology when clinically indicated',allergy:'Primary care or allergy/immunology; emergency care for severe reactions',poisoning:'Poison-control service or emergency department',chest:'Urgent or emergency assessment depending on symptoms; cardiology by referral',respiratory:'Primary care or urgent care; pulmonology when indicated',neurological:'Primary care, urgent/emergency care for red flags; neurology by referral',skin:'Primary care or dermatology',urinary:'Primary care; urology when indicated',mental:'Primary care or licensed mental-health professional',checkup:'Primary care / preventive medicine',general:'Primary care for assessment and referral'};
